# USER ROUTES :

# Home page du site
/:
  controller: MainController
  action: showHomePage
  scope: ""

# page events
/events:
  controller: MainController
  action: page404
  scope: ""

# pages salles
/rooms:
  controller: MainController
  action: page404
  scope: ""

# page 404
/404:
  controller: MainController
  action: page404
  scope: ""

#  ADMIN ROUTES :

#  dashboard bak
/bo:
  controller: HomeController
  action: showDashboard
  scope: "ADMIN MANAGER"

#  page events
/bo/events:
  controller: EventsController
  action: default
  scope: "ADMIN MANAGER"

# formulaire ajout event
/bo/events/new:
  controller: EventsController
  action: showCreateEvent
  scope: "ADMIN MANAGER"

# route POST création event
/bo/events/create:
  controller: EventsController
  action: createEvent
  scope: "ADMIN MANAGER"

# formulaire edition event
/bo/events/edit:
  controller: EventsController
  action: showEditEvent
  scope: "ADMIN MANAGER"

# route POST update event
/bo/events/update:
  controller: EventsController
  action: updateEvent
  scope: "ADMIN MANAGER"

# route POST suppression event
/bo/events/delete:
  controller: EventsController
  action: deleteEvent
  scope: "ADMIN MANAGER"

# page affichage des commentaires
/bo/comments:
  controller: CommentsController
  action: showComments
  scope: "ADMIN MANAGER"

# pages affichage des salles
/bo/rooms:
  controller: RoomsController
  action: default
  scope: "ADMIN MANAGER"

# formulaire ajout salle
/bo/rooms/new:
  controller: RoomsController
  action: showCreateRoom
  scope: "ADMIN MANAGER"

# route POST création salle
/bo/rooms/create:
  controller: RoomsController
  action: createRoom
  scope: "ADMIN MANAGER"

#f ormulaire edition salle
/bo/rooms/edit:
  controller: RoomsController
  action: showEditRoom
  scope: "ADMIN MANAGER"

# route POST edition salle
/bo/rooms/update:
  controller: RoomsController
  action: updateRoom
  scope: "ADMIN MANAGER"

# route POST suppression salle
/bo/rooms/delete:
  controller: RoomsController
  action: deleteRoom
  scope: "ADMIN MANAGER"

# page paramètres du site
/bo/settings:
  controller: SettingsController
  action: showSettings
  scope: "ADMIN"

# page profile utilisateur
/bo/profile:
  controller: MainController
  action: page404
  scope: "ADMIN MANAGER"

# page login
/bo/login:
  controller: AuthenticationController
  action: login
  scope: ""

# page affichage des utilisateurs
/bo/users:
  controller: UsersController
  action: showUsers
  scope: "ADMIN"

# route POST activer/désactiver user
/bo/users/status:
  controller: UsersController
  action: updateStatus
  scope: "ADMIN"

# page inscription manager/admin
/bo/register:
  controller: AuthenticationController
  action: register
  scope: "ADMIN"

# route déconnexion
/bo/logout:
  controller: AuthenticationController
  action: logout
  scope: "ADMIN MANAGER"
