# USER ROUTES :

/:
  controller: MainController
  action: showHomePage

/login:
  controller: AuthenticationController
  action: login

/register:
  controller: AuthenticationController
  action: register

/events:
  controller: MainController
  action: page404

/rooms:
  controller: MainController
  action: page404

/profile:
  controller: MainController
  action: page404

/404:
  controller: MainController
  action: page404

# ADMIN ROUTES :

/admin:
  controller: HomeController
  action: showDashboard

/admin/events:
  controller: EventsController
  action: default

/admin/events/new:
  controller: EventsController
  action: showCreateEvent

/admin/events/create:
  controller: EventsController
  action: CreateEvent

/admin/events/edit:
  controller: EventsController
  action: showEditEvent

/admin/events/update:
  controller: EventsController
  action: UpdateEvent

/admin/users:
  controller: UsersController
  action: showUsers

/admin/comments:
  controller: CommentsController
  action: showComments

/admin/rooms:
  controller: RoomsController
  action: default

/admin/rooms/new:
  controller: RoomsController
  action: showCreateRoom

/admin/rooms/create:
  controller: RoomsController
  action: CreateRoom

/admin/rooms/edit:
  controller: RoomsController
  action: showEditRoom

/admin/rooms/update:
  controller: RoomsController
  action: UpdateRoom

/admin/settings:
  controller: SettingsController
  action: showSettings
