/:
  controller: HomeController
  action: showDashboard

/events:
  controller: EventsController
  action: showEvents

/events/new:
  controller: EventsController
  action: showCreateEvent

/users:
  controller: UsersController
  action: showUsers

/comments:
  controller: CommentsController
  action: showComments

/room:
  controller: RoomsController
  action: showOneRoom

/rooms:
  controller: RoomsController
  action: showRooms

/settings:
  controller: SettingsController
  action: showSettings

/404:
  controller: MainController
  action: page404
