/:
  controller: HomeController
  action: showDashboard

/events:
  controller: EventsController
  action: default

/events/new:
  controller: EventsController
  action: showCreateEvent

/events/create:
  controller: EventsController
  action: CreateEvent

/events/edit:
  controller: EventsController
  action: showEditEvent

/events/update:
  controller: EventsController
  action: UpdateEvent
  security: Login
  role: admin

/users:
  controller: UsersController
  action: showUsers

/comments:
  controller: CommentsController
  action: showComments

/rooms:
  controller: RoomsController
  action: default

/rooms/new:
  controller: RoomsController
  action: showCreateRoom

/rooms/create:
  controller: RoomsController
  action: CreateRoom

/rooms/edit:
  controller: RoomsController
  action: showEditRoom

/rooms/update:
  controller: RoomsController
  action: UpdateRoom

/settings:
  controller: SettingsController
  action: showSettings

/404:
  controller: MainController
  action: page404
